### ISSUE TITLE
runtime performance

### ISSUE THREAD

**Issue by branaway** [pk11/play-jaxrs#2]
Since all the routes are dynamically built when the handlerFor(...), would that have performance impact at runtime?
- A page can have refs to quite a few assets. Will each retrieval to the asset invoke the  path scanning and route table regeneration?
- And in production mode too?

**Comment by pk11** [comment]
We used this in production and we did not notice any significant hit due to the reflective calls. If you check the techempower benchmarks, `dropwizard` (another jax-rs based solution) was doing just fine. Obviously, the easiest if you see it for yourself. In terms of dispatching routes, there is no difference between production and dev mode.

I am not sot sure what you mean by your assets comment. Assets dispatching was not really changed here - we are using the same controller as a native play app.
